### ISSUE TITLE
Announce?

### ISSUE THREAD

**Issue by martindurant** [dr-leo/intake_sdmx#2]
@dr-leo , I notice you have continued to develop this repo (sorry for not paying closer attention). Do you think it's time to publish on pypi, expose the docs and include in Intake's like of known drivers?

**Comment by dr-leo** [comment]
I would hope to release and publish the docs soon. To points:

1. selection of many values for a user_param. I vainly tried two
things: (1) subclass UserParameter providing a custom validate()
method. But this is not executed as for some reason the subclass
instance is replaced by the original; and (2): subclass list() to
specify the allowed values within UserParameter, providing a custom
__contains__ method. But this, too, is not executed as the original
list type is used. Is there an issue with copying things? - I consider
the lack of multiple values for a param as msjor limitation. I would
release regardless if there is no hope to fix this in the near future.

 2. The other issue you fixed in the intake repo was about propagating
args to instance using configure_new(). This issue impacts on code
examples for intake_sdmx. Can I suggest that you do a new intake
release first?

**Comment by martindurant** [comment]
1., I would think that (2) is marginally easier to implement, and I'd be happy to help make it work. Can you show me in more detail what the problem is? If we get something nice, this can be upstreamed into Intake

2. agree, I can release. Let's see where we get with 1. first, as that could be contributed to the main repo.

**Comment by dr-leo** [comment]
One could optionally add some code that produces meta-data on plotting. But this is certainly not my area of expertise although I realize from the docs that it should be a matter of a few lines

**Comment by martindurant** [comment]
Do you suppose that the metadata from the data providers includes useful information about how to present the information, or that we are in a decent position to know which columns are most appropriate? pandas' `plot()` function (or `hvplot` and others) tend to have a fairly reasonable guess at how to graphically show a dataframe.

**Comment by dr-leo** [comment]
The pandas object maybe multi indexed serious or a data frame with 500 columns or anything in between. So I guess it will be hard to anticipate the best solution. I would leave it to the plotting back and to analyze the data frame.

**Comment by martindurant** [comment]
> I would leave it to the plotting back and to analyze the data frame.

Or indeed the user - I agree.

**Comment by dr-leo** [comment]
OK. So is there any code to be added to enable this behavior?

**Comment by martindurant** [comment]
No, no need to add any plotting info if we aren't sure what would work well.

On July 7, 2021 2:31:19 PM EDT, dr-leo ***@***.***> wrote:
>OK. So is there any code to be added to enable this behavior?
>
>On 07/07/2021, Martin Durant ***@***.***> wrote:
>>> I would leave it to the plotting back and to analyze the data frame.
>>
>> Or indeed the user - I agree.
>>
>> --
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub:
>> https://github.com/dr-leo/intake_sdmx/issues/2#issuecomment-875815319
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/dr-leo/intake_sdmx/issues/2#issuecomment-875834356

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dr-leo** [comment]
See this branch:

https://github.com/dr-leo/intake_sdmx/tree/allow_multiple_codes

The subclass used as list of allowed values for enumerated dimensions  such as FREQ = ['A', ''annual', 'Q', 'quarterly'] has the stupid name PowerSet (line 19). See the simple __contains__ method. It is instantiated in line 215.

There is also a subclass of UserParameter which overwrites the validate() method.

But neither approach works. And I doubt that any of them will, at least because a DataSource created from yaml would not honor the subclass. Rather it would be populated with lists. And when subclassing UserParameter, how can the intake machinery know, when instantiating an instance from yaml, that it should use the subclass?

I think the most elegant solution would be to modify the intake main repo by addint to UserParameter a param, say, `allow_many`:bool which tells the validate method to check for an iterable of type, all of which would have to validate against the list of allowed values.

Well, enabling UserParemeter subclasses or allowed list subclasses would be OK as well. This would even be more powerful than the above as one could du fancy stuff as I'd like to do: a string like "USD+JPY+EUR" would validate against the list of currency codes...

**Comment by dr-leo** [comment]
This is obsolete. I guess I'll release soon. Any discussions will happen on intake/intake#593.
